= mavennatives

== Maven plugin

== Eclipse plugin (Eclipse M2E Extension)

== about the project

Automatically exported from code.google.com/p/mavennatives which was at version 0.0.7.
This maven plugin has then been renamed to "nativedependencies-maven-plugin" (to follow Apache Maven conventions) and groupid changed to com.teamtter.mavennatives.


= How to use the Maven plugin

== Maven dependency

The plugin is available from Maven Central:

[source,xml]
-------------------------------------------
<dependency>
    <groupId>com.teamtter.mavennatives</groupId>
    <artifactId>nativedependencies-maven-plugin</artifactId>
    <version>0.0.8</version>
</dependency>
-------------------------------------------
 
== Options
 
 TODO...
 
 = How to use the Eclipse M2E extension 
 
= Compiling the code

you need a real Java 7 to compile as we face errors with Java 8's javac.

= Done

* use real Java 5 annotations
* parameter to be able to skip the plugin execution (overridable through a variable)
* add parameters to auto-detect platform and get only platform specific libs
* transparently handle misc compression format (zip, tar, tgz, 7zip...) and single file not compressed deps (.dll, .so, .dylib...)
* handle transitive native dependencies (it already worked !)
* m2e connector => make Eclipse plugin automatically add -Djava.library.path (to run targets, junit tests, etc)
* keep a cache of the signature (md5, sha1, date ???) for each compressed file to avoid uncompressing it again if it has not changed => this has been done through saving the last modification date of the artifacts in a json file in target/natives dir

= Problematic that this plugin will try to solve

* enable a native developer to compile it's native lib (we don't care how) and place them in a folder where they won't be overwriten on each mvn run by the ones in .m2 or Archiva
** use another folder and play on the order of folder declaration in the -Djava.library.path ???
** do not overwrite if newer
** another solution ?
* streamline command-line VS Eclipse use => if it works on command-line, it should work in Eclipse without touching anything !


= Reasons for forking original project

* add finer grain control over what natives dependencies will be unpacked.
* familiarize myself with the dev of Maven plugins.
* improve eclipse plugin
* finally find a way to prevent each and every project using native libs to have to manually (god I hate this word!) configure the -Djava.library.path and LD_LIBRARY_PATH

License : Apache License 2.0 
